name: KaniAction
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Kani
        run: |
          cargo install --locked kani-verifier
          cargo-kani setup

      - name: Run Kani
        run: kani test.rs